version: '3.8'

services:
  Auth_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ashif1234
      POSTGRES_DB: rkrk_auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    depends_on:
      - Auth_db
      - redis
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.development
    # Added volume mapping for development
    volumes:
      - .:/app
      - /app/node_modules
      - ./secrets:/app/secrets
  # common-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/common/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env.development
  #   # Added volume mapping for development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  postgres_data:
