// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: auth-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export enum Role {
  PASSENGER = 0,
  DRIVER = 1,
  ADMIN = 2,
  VEHICLE_OWNER = 3,
  UNRECOGNIZED = -1,
}

export interface MessageResponse {
  message: string;
}

export interface User {
  id: string;
  mobile: string;
  name: string;
  roles: Role[];
  activePerspective: Role;
  isActive: boolean;
  profilePicture: string;
  kycStatus: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AuthResponse {
  user: User | undefined;
  accessToken: string;
  refreshToken: string;
}

export interface SendOtpRequest {
  mobile: string;
}

export interface VerifyOtpRequest {
  mobile: string;
  otp: string;
  ip: string;
  userAgent: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
  ip: string;
  userAgent: string;
}

export interface LogoutRequest {
  userId: string;
  jti: string;
  tokenExp: number;
  refreshToken: string;
}

export interface LogoutAllDevicesRequest {
  userId: string;
}

export interface GetMeRequest {
  userId: string;
}

export interface GetMeResponse {
  user: User | undefined;
}

export interface UpdateMeRequest {
  userId: string;
  name?: string | undefined;
  profileImage?: string | undefined;
}

export interface UpdateMeResponse {
  message: string;
  user: User | undefined;
  accessToken: string;
}

export interface SwitchPerspectiveRequest {
  userId: string;
  perspective: Role;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  sendOtp(request: SendOtpRequest): Observable<MessageResponse>;

  verifyOtp(request: VerifyOtpRequest): Observable<AuthResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<AuthResponse>;

  logout(request: LogoutRequest): Observable<MessageResponse>;

  logoutAllDevices(request: LogoutAllDevicesRequest): Observable<MessageResponse>;

  getMe(request: GetMeRequest): Observable<GetMeResponse>;

  updateMe(request: UpdateMeRequest): Observable<UpdateMeResponse>;

  switchPerspective(request: SwitchPerspectiveRequest): Observable<UpdateMeResponse>;
}

export interface AuthServiceController {
  sendOtp(request: SendOtpRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  verifyOtp(request: VerifyOtpRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  refreshToken(request: RefreshTokenRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  logout(request: LogoutRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  logoutAllDevices(
    request: LogoutAllDevicesRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMe(request: GetMeRequest): Promise<GetMeResponse> | Observable<GetMeResponse> | GetMeResponse;

  updateMe(request: UpdateMeRequest): Promise<UpdateMeResponse> | Observable<UpdateMeResponse> | UpdateMeResponse;

  switchPerspective(
    request: SwitchPerspectiveRequest,
  ): Promise<UpdateMeResponse> | Observable<UpdateMeResponse> | UpdateMeResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "sendOtp",
      "verifyOtp",
      "refreshToken",
      "logout",
      "logoutAllDevices",
      "getMe",
      "updateMe",
      "switchPerspective",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
