// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: search-and-catalog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'searchAndCatalog';

export interface Vehicle {
  id: string;
  ownerId: string;
  vehicleCategory: string;
  make: string;
  model: string;
  variant: string;
  registrationNumber: string;
  seatingCapacity: string;
  color: string;
  hasAC: boolean;
  manufacturingYear: number;
  serviceRadius: number;
  homeLat: number;
  homeLng: number;
  homeAddress: string;
  vehiclePhotos: string[];
  status: string;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  blocks: Block[];
  fuelType: string;
  transmission: string;
  plateType?: string;
  commercialPermitNumber?: string;
  permitType?: string;
  permitExpiryDate?: string;
  perKmOutstation?: number;
  perHourLocal?: number;
  minimumBookingHours?: number;
  nightChargePercentage?: number;
  eventPackage?: any;
  advancePercentage?: number;
  rtoRawDataJson?: string;
}

export interface UpdatePlateTypeRequest {
  vehicleId: string;
  plateType: string;
  commercialPermitNumber?: string;
  permitType?: string;
  permitExpiryDate?: string;
}

export interface SetPricingRequest {
  vehicleId: string;
  perKmOutstation?: number;
  perHourLocal?: number;
  minimumBookingHours?: number;
  nightChargePercentage?: number;
  eventPackage?: any;
}

export interface GetPricingRequest {
  vehicleId: string;
}

export interface GetPricingResponse {
  vehicleId: string;
  pricing: any;
}

export interface Block {
  id: string;
  startDate: string;
  endDate: string;
  reason: string;
  bookingId: string;
  createdAt: string;
}

export interface RegisterVehicleRequest {
  ownerId: string;
  vehicleCategory: string;
  make: string;
  model: string;
  variant: string;
  registrationNumber: string;
  seatingCapacity: string;
  color: string;
  hasAC: boolean;
  manufacturingYear: number;
  serviceRadius: number;
  homeLat: number;
  homeLng: number;
  homeAddress: string;
  vehiclePhotos: string[];
  fuelType: string;
  transmission: string;
  plateType?: string;
  rtoRawDataJson?: string;
}

export interface GetVehicleRequest {
  id: string;
}

export interface ListVehiclesRequest {
  ownerId: string;
  status: string;
}

export interface UpdateVehicleRequest {
  id: string;
  ownerId: string;
  vehicleCategory: string;
  make: string;
  model: string;
  variant: string;
  registrationNumber: string;
  seatingCapacity: string;
  color: string;
  hasAC: boolean;
  manufacturingYear: number;
  serviceRadius: number;
  homeLat: number;
  homeLng: number;
  homeAddress: string;
  vehiclePhotos: string[];
  fuelType: string;
  transmission: string;
  plateType?: string;
  rtoRawDataJson?: string;
}

export interface DeleteVehicleRequest {
  id: string;
  ownerId: string;
}

export interface DeleteVehicleResponse {
  deleted: boolean;
}

export interface ActivateVehicleRequest {
  id: string;
}

export interface SuspendVehicleRequest {
  id: string;
}

export interface UpdateVehicleOnlineStatusRequest {
  id: string;
  ownerId: string;
  isAvailable: boolean;
}

export interface UpdateOwnerVehiclesAvailabilityRequest {
  ownerId: string;
  isAvailable: boolean;
}

export interface BlockVehicleRequest {
  id: string;
  ownerId: string;
  /** 'YYYY-MM-DD' */
  startDate: string;
  /** 'YYYY-MM-DD' */
  endDate: string;
  reason: string;
  bookingId: string;
}

export interface BlockAllOwnerVehiclesRequest {
  ownerId: string;
  /** 'YYYY-MM-DD' */
  startDate: string;
  /** 'YYYY-MM-DD' */
  endDate: string;
  reason: string;
}

export interface UnblockVehicleRequest {
  blockId: string;
  ownerId: string;
}

export interface UnblockVehicleResponse {
  unblocked: boolean;
}

export interface UnblockAllOwnerVehiclesRequest {
  ownerId: string;
}

export interface IsVehicleAvailableRequest {
  vehicleId: string;
  startDate: string;
  endDate: string;
}

export interface IsVehicleAvailableResponse {
  isAvailable: boolean;
}

export interface SearchVehiclesRequest {
  from: string;
  to: string;
  date: string;
  time: string;
  vehicleType: string;
  seats: number;
  color: string;
  ac?: boolean | undefined;
}

export interface GetMyVehiclesRequest {
  ownerId: string;
}

export interface GetVehicleByIdRequest {
  id: string;
}

export interface SearchVehiclesByCityRequest {
  city: string;
}

export interface GetAllVehiclesRequest {}

export interface VehicleResponse {
  vehicle: Vehicle | undefined;
}

export interface ListVehiclesResponse {
  vehicles: Vehicle[];
}

export const SEARCH_AND_CATALOG_PACKAGE_NAME = 'searchAndCatalog';

export interface SearchAndCatalogServiceClient {
  /** Catalog / Vehicle CRUD */

  registerVehicle(request: RegisterVehicleRequest): Observable<VehicleResponse>;

  getVehicle(request: GetVehicleRequest): Observable<VehicleResponse>;

  listVehicles(request: ListVehiclesRequest): Observable<ListVehiclesResponse>;

  updateVehicle(request: UpdateVehicleRequest): Observable<VehicleResponse>;

  deleteVehicle(
    request: DeleteVehicleRequest,
  ): Observable<DeleteVehicleResponse>;

  /** Admin Controls */

  activateVehicle(request: ActivateVehicleRequest): Observable<VehicleResponse>;

  suspendVehicle(request: SuspendVehicleRequest): Observable<VehicleResponse>;

  /** Online/Offline Toggles */

  updateVehicleOnlineStatus(
    request: UpdateVehicleOnlineStatusRequest,
  ): Observable<VehicleResponse>;

  updateOwnerVehiclesAvailability(
    request: UpdateOwnerVehiclesAvailabilityRequest,
  ): Observable<ListVehiclesResponse>;

  /** Date-Specific Blocking */

  blockVehicle(request: BlockVehicleRequest): Observable<VehicleResponse>;

  blockAllOwnerVehicles(
    request: BlockAllOwnerVehiclesRequest,
  ): Observable<ListVehiclesResponse>;

  unblockVehicle(
    request: UnblockVehicleRequest,
  ): Observable<UnblockVehicleResponse>;

  unblockAllOwnerVehicles(
    request: UnblockAllOwnerVehiclesRequest,
  ): Observable<ListVehiclesResponse>;

  /** Availability Check */

  isVehicleAvailable(
    request: IsVehicleAvailableRequest,
  ): Observable<IsVehicleAvailableResponse>;

  /** Search */

  searchVehicles(
    request: SearchVehiclesRequest,
  ): Observable<ListVehiclesResponse>;

  getMyVehicles(
    request: GetMyVehiclesRequest,
  ): Observable<ListVehiclesResponse>;

  getVehicleById(request: GetVehicleByIdRequest): Observable<VehicleResponse>;

  searchVehiclesByCity(
    request: SearchVehiclesByCityRequest,
  ): Observable<ListVehiclesResponse>;

  getAllVehicles(
    request: GetAllVehiclesRequest,
  ): Observable<ListVehiclesResponse>;

  updatePlateType(request: UpdatePlateTypeRequest): Observable<VehicleResponse>;

  setPricing(request: SetPricingRequest): Observable<VehicleResponse>;

  getPricing(request: GetPricingRequest): Observable<GetPricingResponse>;
}

export interface SearchAndCatalogServiceController {
  /** Catalog / Vehicle CRUD */

  registerVehicle(
    request: RegisterVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  getVehicle(
    request: GetVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  listVehicles(
    request: ListVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  updateVehicle(
    request: UpdateVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  deleteVehicle(
    request: DeleteVehicleRequest,
  ):
    | Promise<DeleteVehicleResponse>
    | Observable<DeleteVehicleResponse>
    | DeleteVehicleResponse;

  /** Admin Controls */

  activateVehicle(
    request: ActivateVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  suspendVehicle(
    request: SuspendVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  /** Online/Offline Toggles */

  updateVehicleOnlineStatus(
    request: UpdateVehicleOnlineStatusRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  updateOwnerVehiclesAvailability(
    request: UpdateOwnerVehiclesAvailabilityRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  /** Date-Specific Blocking */

  blockVehicle(
    request: BlockVehicleRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  blockAllOwnerVehicles(
    request: BlockAllOwnerVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  unblockVehicle(
    request: UnblockVehicleRequest,
  ):
    | Promise<UnblockVehicleResponse>
    | Observable<UnblockVehicleResponse>
    | UnblockVehicleResponse;

  unblockAllOwnerVehicles(
    request: UnblockAllOwnerVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  /** Availability Check */

  isVehicleAvailable(
    request: IsVehicleAvailableRequest,
  ):
    | Promise<IsVehicleAvailableResponse>
    | Observable<IsVehicleAvailableResponse>
    | IsVehicleAvailableResponse;

  /** Search */

  searchVehicles(
    request: SearchVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  getMyVehicles(
    request: GetMyVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  getVehicleById(
    request: GetVehicleByIdRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  searchVehiclesByCity(
    request: SearchVehiclesByCityRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  getAllVehicles(
    request: GetAllVehiclesRequest,
  ):
    | Promise<ListVehiclesResponse>
    | Observable<ListVehiclesResponse>
    | ListVehiclesResponse;

  updatePlateType(
    request: UpdatePlateTypeRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  setPricing(
    request: SetPricingRequest,
  ): Promise<VehicleResponse> | Observable<VehicleResponse> | VehicleResponse;

  getPricing(
    request: GetPricingRequest,
  ):
    | Promise<GetPricingResponse>
    | Observable<GetPricingResponse>
    | GetPricingResponse;
}

export function SearchAndCatalogServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'registerVehicle',
      'getVehicle',
      'listVehicles',
      'updateVehicle',
      'deleteVehicle',
      'activateVehicle',
      'suspendVehicle',
      'updateVehicleOnlineStatus',
      'updateOwnerVehiclesAvailability',
      'blockVehicle',
      'blockAllOwnerVehicles',
      'unblockVehicle',
      'unblockAllOwnerVehicles',
      'isVehicleAvailable',
      'searchVehicles',
      'getMyVehicles',
      'getVehicleById',
      'searchVehiclesByCity',
      'getAllVehicles',
      'updatePlateType',
      'setPricing',
      'getPricing',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('SearchAndCatalogService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('SearchAndCatalogService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const SEARCH_AND_CATALOG_SERVICE_NAME = 'SearchAndCatalogService';
