export enum OrderStatus {
  OWNER_PENDING = 'OWNER_PENDING',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  CONFIRMED = 'CONFIRMED',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
